// Example: side-effect registration like pprof; call example gRPC service via POST /grpc-gateway.
// Descriptors are generated by make gen into the SDK core directory, shipped with SDK; gateway loads from core package dir at runtime.
package main

import (
	"log"
	"net/http"

	_ "github.com/keicoqk/gateway/sdk"
)

func main() {
	log.Println("HTTP gateway listening on :8080 (POST /grpc-gateway)")
	log.Fatal(http.ListenAndServe(":8080", nil))
}
